Fix scripts, enhance dump, cleanup.

diff --git a/scripts/composer b/scripts/composer
--- a/scripts/composer
+++ b/scripts/composer
@@ -6,12 +6,11 @@
 # |____/ \____| |____/|_|   \__,_| .__/ \__,_|_|
 #                               |_|
 #
-# Helper to run mysql dump/restore, part of Docker Compose Drupal project.
-# Based on Bash simple Boilerplate.
+# Helper to execute Composer as a standalone docker container.
 # https://github.com/Mogtofu33/docker-compose-drupal
 #
 # Usage:
-#   pgsql dump | restore
+#   ./composer about
 #
 # Depends on:
 #  docker
@@ -27,6 +26,10 @@ while [ -h "$_SOURCE" ]; do # resolve $_SOURCE until the file is no longer a sym
 done
 _DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"
 
+if [ ! -f $_DIR/helpers/common.sh ]; then
+  echo -e "Missing helpers/common.sh file."
+  exit 1
+fi
 source $_DIR/helpers/common.sh
 
 ###############################################################################
@@ -48,59 +51,19 @@ _print_help() {
  |____/ \____| |____/|_|   \__,_| .__/ \__,_|_|
                                 |_|
 
-Helper to dump and restore MYSQL db with drush.
+Helper to execute Composer as a standalone docker container, see
+https://getcomposer.org/doc/03-cli.md for commands details.
+
+For require command it's recommended to use --ignore-platform and 
+--no-scripts options.
 
 Usage:
-  ${_ME} [dump | restore]
+  ${_ME} [status | require | remove | outdated | ... ]
   ${_ME} -h | --help
 
 Options:
   -h --help  Show this screen.
 HEREDOC
-}
-
-###############################################################################
-# Program Functions
-###############################################################################
-
-_dump() {
-
-  $_DOCKER exec $tty "${PROJECT_CONTAINER_NAME}" mkdir -p "${PROJECT_CONTAINER_DUMP}"
-
-  # We use drush as it manage database authentication.
-  $_DOCKER exec \
-    $tty \
-    --interactive \
-    "${PROJECT_CONTAINER_NAME}" \
-    "${DRUSH_BIN}" "${PROJECT_CONTAINER_ROOT}" sql-dump \
-      --skip-tables-list=migrate_* \
-      --structure-tables-list=cache*,history,node_counter,search_*,sessions,watchdog \
-      --result-file=${PROJECT_CONTAINER_DUMP}/dump_${_NOW}.sql
-}
-
-_drop() {
-  $_DOCKER exec \
-    $tty \
-    --interactive \
-    --user "${PROJECT_CONTAINER_USER}" \
-    "${PROJECT_CONTAINER_NAME}" \
-    "${DRUSH_BIN}" "${PROJECT_CONTAINER_ROOT}" -y sql-drop
-}
-
-_restore() {
-
-  # $_DOCKER exec $tty "${PROJECT_CONTAINER_NAME}" mkdir -p "${PROJECT_CONTAINER_DUMP}"
-
-  # Drush failed because of path.
-  # $_DOCKER exec \
-  #   --user "${PROJECT_CONTAINER_USER}" \
-  #   "${PROJECT_CONTAINER_NAME}" \
-  #     sh -c 'exec /var/www/localhost/drupal/vendor/bin/drush --root=/var/www/localhost/drupal/web sql-cli < /docker-entrypoint-initdb.d/dump.sql'
-
-  $_DOCKER exec \
-    --user "${MYSQL_CONTAINER_USER}" \
-    "${PROJECT_CONTAINER_MYSQL}" \
-      sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD" $MYSQL_DATABASE < /docker-entrypoint-initdb.d/dump.sql'
 }
 
 ###############################################################################
@@ -118,22 +81,17 @@ _main() {
 
   _check_dependencies_docker
 
-  # Run actions.
-  if [[ "${1:-}" =~ ^dump$ ]]
+  # Avoid complex option parsing when only one program option is expected.
+  if [[ "${1:-}" =~ ^-h|--help$  ]]
   then
-    _dump
-  elif [[ "${1:-}" =~ ^restore$ ]]
-  then
-    _drop
-    _restore
-  elif [[ "${1:-}" =~ ^drop$ ]]
-  then
-    _drop
-  else
     _print_help
+  else
+    _docker_run \
+      --volume "${_DRUPAL_ROOT}":/app \
+      composer --working-dir=/app "$@"
   fi
+
 }
 
 # Call `_main` after everything has been defined.
 _main "$@"
-
diff --git a/scripts/drupal b/scripts/drupal
--- a/scripts/drupal
+++ b/scripts/drupal
@@ -8,11 +8,13 @@ while [ -h "$_SOURCE" ]; do # resolve $_SOURCE until the file is no longer a sym
 done
 _DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"
 
+if [ ! -f $_DIR/helpers/common.sh ]; then
+  echo -e "Missing helpers/common.sh file."
+  exit 1
+fi
 source $_DIR/helpers/common.sh
 
-$_DOCKER exec \
-  $tty \
-  --interactive \
+_docker_exec \
   --user "${PROJECT_CONTAINER_USER}" \
   "${PROJECT_CONTAINER_NAME}" \
-  "${DRUSH_BIN}" "${PROJECT_CONTAINER_ROOT}" "$@"
+  "${DRUPAL_BIN}" "${PROJECT_CONTAINER_ROOT}" "$@"
diff --git a/scripts/pgsql b/scripts/pgsql
--- a/scripts/pgsql
+++ b/scripts/pgsql
@@ -27,6 +27,10 @@ while [ -h "$_SOURCE" ]; do # resolve $_SOURCE until the file is no longer a sym
 done
 _DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"
 
+if [ ! -f $_DIR/helpers/common.sh ]; then
+  echo -e "Missing helpers/common.sh file."
+  exit 1
+fi
 source $_DIR/helpers/common.sh
 
 ###############################################################################
@@ -51,7 +55,7 @@ _print_help() {
 Helper to dump and restore PGSQL db with pg_dump and pg_restore.
 
 Usage:
-  ${_ME} [dump | restore]
+  ${_ME} [dump | restore | list]
   ${_ME} -h | --help
 
 Options:
@@ -59,53 +63,81 @@ Options:
 HEREDOC
 }
 
+_DUMP_FILE="dump.pg_dump"
+
 ###############################################################################
 # Program Functions
 ###############################################################################
 
 _dump() {
-  docker exec $tty "${PROJECT_CONTAINER_PGSQL}" mkdir -p "${PROJECT_CONTAINER_DUMP}"
-  docker exec $tty "${PROJECT_CONTAINER_PGSQL}" chown -R "$PGSQL_USER_ID" "${PROJECT_CONTAINER_DUMP}"
-
-  # If we have an existing dump.
-  docker exec $tty "${PROJECT_CONTAINER_PGSQL}" rm -f "${PROJECT_CONTAINER_DUMP}"/dump_${_NOW}.pg_dump
-
-  docker exec \
-    $tty \
+  _DUMP_FILE="dump_${_NOW}.pg_dump"
+  _docker_exec \
     --user "${PGSQL_USER}" \
     "${PROJECT_CONTAINER_PGSQL}" \
-      pg_dump -d "${POSTGRES_DB}" -U "${PGSQL_USER}" -hlocalhost -Fc -c -b -v -f ${PROJECT_CONTAINER_DUMP}/dump_${_NOW}.pg_dump \
+      pg_dump -d "${POSTGRES_DB}" -U "${PGSQL_USER}" -hlocalhost -Fc -c -b -v -f ${PROJECT_CONTAINER_DUMP}/${_DUMP_FILE} \
       --exclude-table-data '*.cache*' --exclude-table-data '*.cachetags*' \
       --exclude-table-data '*.watchdog*' --exclude-table-data '*.node_access*' \
       --exclude-table-data '*.search_api_db_*' --exclude-table-data '*.sessions*' \
-      --exclude-table-data '*.sessions*' --exclude-table-data '*.webprofiler*' 
+      --exclude-table-data '*.sessions*' --exclude-table-data '*.webprofiler*'
+
+  echo -e "Database dump saved to ${_DUMP_FILE}"
 }
 
 _restore() {
+  _select_dump
+  echo -e "Restoring $_DUMP_FILE..."
+  if [ ! -z "$_DUMP_FILE" ]; then
+    _docker_exec \
+      --user "${PGSQL_USER}" \
+      "${PROJECT_CONTAINER_PGSQL}" \
+        dropdb --if-exists "${POSTGRES_DB}"
+    _docker_exec \
+      --user "${PGSQL_USER}" \
+      "${PROJECT_CONTAINER_PGSQL}" \
+        createdb -e --owner="${PGSQL_USER}" "${POSTGRES_DB}"
+    _docker_exec \
+      --user "${PGSQL_USER}" \
+      "${PROJECT_CONTAINER_PGSQL}" \
+        psql -e -d ${POSTGRES_DB} -c "GRANT ALL ON database ${POSTGRES_DB} TO ${PGSQL_USER}"
+    _docker_exec \
+      --user "${PGSQL_USER}" \
+      "${PROJECT_CONTAINER_PGSQL}" \
+        pg_restore -h localhost -p 5432 --no-owner --role="${PGSQL_USER}" -U "${PGSQL_USER}" -d "${POSTGRES_DB}" -v ${PROJECT_CONTAINER_DUMP}/${_DUMP_FILE}
+  fi
+}
 
-  docker exec $tty "${PROJECT_CONTAINER_PGSQL}" mkdir -p "${PROJECT_CONTAINER_DUMP}"
-  docker exec $tty "${PROJECT_CONTAINER_PGSQL}" chown -R "${PGSQL_USER_ID}" "${PROJECT_CONTAINER_DUMP}"
+_list_dump() {
+  echo -e "Available dump files:"
+  _docker_exec "${PROJECT_CONTAINER_PGSQL}" ls -lah "${PROJECT_CONTAINER_DUMP}"
+}
 
-  docker exec \
-    $tty \
-    --user "${PGSQL_USER}" \
-    "${PROJECT_CONTAINER_PGSQL}" \
-      dropdb --if-exists "${POSTGRES_DB}"
-  docker exec \
-    $tty \
-    --user "${PGSQL_USER}" \
-    "${PROJECT_CONTAINER_PGSQL}" \
-      createdb -e --owner="${PGSQL_USER}" "${POSTGRES_DB}"
-  docker exec \
-    $tty \
-    --user "${PGSQL_USER}" \
-    "${PROJECT_CONTAINER_PGSQL}" \
-      psql -e -d ${POSTGRES_DB} -c "GRANT ALL ON database ${POSTGRES_DB} TO ${PGSQL_USER}"
-  docker exec \
-    $tty \
-    --user "${PGSQL_USER}" \
-    "${PROJECT_CONTAINER_PGSQL}" \
-      pg_restore -h localhost -p 5432 --no-owner --role="${PGSQL_USER}" -U "${PGSQL_USER}" -d "${POSTGRES_DB}" -v ${PROJECT_CONTAINER_DUMP}/dump.pg_dump
+_ensure_dir() {
+  # No interactive, ensure permissions.
+  $_DOCKER exec $tty "${PROJECT_CONTAINER_PGSQL}" chown -R ${PGSQL_USER_ID} "${PROJECT_CONTAINER_DUMP}"
+}
+
+_select_dump() {
+
+  _DUMPS=$($_DOCKER exec --user "${PGSQL_USER}" "${PROJECT_CONTAINER_PGSQL}"  ls "${PROJECT_CONTAINER_DUMP}")
+  _DUMPS=(`echo $_DUMPS | sed 's/ /\n/g'`)
+
+  echo -e "Select a dump file:"
+  select opt in "${_DUMPS[@]}" "Cancel"; do
+    case $opt in
+      *.pg_dump)
+        _DUMP_FILE=$opt
+        break
+        ;;
+      "Cancel")
+        echo "You chose to cancel"
+        _DUMP_FILE=""
+        break
+        ;;
+      *)
+        echo "This is not a number"
+        ;;
+    esac
+  done
 }
 
 ###############################################################################
@@ -124,11 +156,12 @@ _main() {
   _check_dependencies_docker
 
   # Run actions.
-  if [[ "${1:-}" =~ ^dump$ ]]
-  then
+  if [[ "${1:-}" =~ ^list$ ]]; then
+    _list_dump
+  elif [[ "${1:-}" =~ ^dump$ ]]; then
+    _ensure_dir
     _dump
-  elif [[ "${1:-}" =~ ^restore$ ]]
-  then
+  elif [[ "${1:-}" =~ ^restore$ ]]; then
     _restore
   else
     _print_help
diff --git a/scripts/phpqa b/scripts/phpqa
--- a/scripts/phpqa
+++ b/scripts/phpqa
@@ -6,11 +6,11 @@
 # |____/ \____| |____/|_|   \__,_| .__/ \__,_|_|
 #                               |_|
 #
-# Helper to execute Composer as a standalone docker container.
+# Helper to execute PhpQA as a standalone docker container.
 # https://github.com/Mogtofu33/docker-compose-drupal
 #
 # Usage:
-#   composer.sh
+#   ./phpqa tools
 #
 # Depends on:
 #  docker
@@ -26,6 +26,10 @@ while [ -h "$_SOURCE" ]; do # resolve $_SOURCE until the file is no longer a sym
 done
 _DIR="$( cd -P "$( dirname "$_SOURCE" )" && pwd )"
 
+if [ ! -f $_DIR/helpers/common.sh ]; then
+  echo -e "Missing helpers/common.sh file."
+  exit 1
+fi
 source $_DIR/helpers/common.sh
 
 ###############################################################################
@@ -53,7 +57,7 @@ For require command it's recommended to use --ignore-platform-
 and --no-scripts options.
 
 Usage:
-  ${_ME} [status | require | remove | outdated | ... ]
+  ${_ME} [tools |... ]
   ${_ME} -h | --help
 
 Options:
@@ -81,15 +85,8 @@ _main() {
   then
     _print_help
   else
-    $_DOCKER run \
-      $tty \
-      --interactive \
-      --rm \
-      --user "${LOCAL_UID}":"${LOCAL_GID}" \
-      --volume /etc/passwd:/etc/passwd:ro \
-      --volume /etc/group:/etc/group:ro \
-      --volume "${_DRUPAL_ROOT}":/app \
-        composer --working-dir=/app "$@"
+    _docker_run \
+      zdenekdrahos/phpqa:v1.19.0 phpqa "$@"
   fi
 
 }
